branches:
  - master
  - master-release-test
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  [![https://hub.docker.com/r/litetex/pulldetachedremote/tags?name=$RESOLVED_VERSION](https://img.shields.io/badge/docker-$RESOLVED_VERSION-%232684ff)](https://hub.docker.com/r/litetex/pulldetachedremote/tags?name=$RESOLVED_VERSION)

  ``docker pull litetex/pulldetachedremote:$RESOLVED_VERSION``
  
  ## Changes
  
  $CHANGES
